# Generated by Django 5.2.4 on 2025-07-17 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.category'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='livestream_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
