# Generated by Django 5.2.4 on 2025-07-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp',
            field=models.ManyToManyField(blank=True, related_name='rsvped_events', to='event.participant'),
        ),
    ]
